name: sports_repository
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true