name: sports_list
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

  component_library:
    path: ../../component_library
  domain_entities:
    path: ../../domain_entities
  sports_repository:
    path: ../../sports_repository
  provider: ^6.1.2
  logger: ^2.5.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.1.0
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true