name: component_library
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

# flutter:
#   used-material-design: true

assets:
  - lib/src/assets/images/
