name: component_library
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  sports_list:
    path: ../features/sports_list
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl: ^0.20.2
  http: ^1.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
#   used-material-design: true

  assets:
    - lib/src/assets/images/svg/
    - lib/src/assets/images/
    - lib/src/assets/images/player_images/
